/*
 * HIROControllerRtc.h
 *
 *  Created on: 2011-10-05
 *  Auto Generated by: gp.rb
 */

#ifndef HIROCONTROLLERRTC_H
#define HIROCONTROLLERRTC_H

#include "../Grasp/GraspController.h"
#include "HIROControllerRTC/HIROController.hh"
#include "HIROControllerRTC/HIROController.h"

namespace grasp {

class HIROControllerRtc {
	public:
		HIROControllerRtc() {}
		~HIROControllerRtc() {}
		static HIROControllerRtc* instance();
		int RtcStart();
		static void MyModuleInit(RTC::Manager* manager);

		::HIROController * comp_;
};

}

#endif /* HIROCONTROLLER_H */
